# DEFAULT_ROWS = 7
# DEFAULT_COLS = 21

DEFAULT_ROWS = 12
DEFAULT_COLS = 12


DEFAULT_MAX_LENGTH = 160
NEWLINE_CHAR = "\n"
EMPTY_CHAR = "□"
FULL_CHAR = "■"
TOP_HALF_CHAR = "▀"
BOTTOM_HALF_CHAR = "▄"

ALIVE_CHARS = [FULL_CHAR, TOP_HALF_CHAR, BOTTOM_HALF_CHAR]
DEAD_CHARS = [EMPTY_CHAR]


TALL_BLOCK_CHAR = "█"
