name: Conway Bio Updater

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-bio:
    runs-on: ubuntu-latest
    container:
      image: tiangolo/uvicorn-gunicorn:python3.11-slim  # Comes with requests pre-installed
      
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1    # Shallow clone for faster checkout
    
    - name: Run Conway Bio updater
      env:
        PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
      run: python conway-bio.py 