name: Conway Bio Updater

on:
  # schedule:
  #   - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-bio:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/conway-runner:latest
      
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1    # Shallow clone for faster checkout
    
    - name: Install lifegame package
      run: |
        cd lifegame
        uv pip install -e .

    - name: Run Conway Bio updater
      env:
        PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
      run: python -m lifegame --bio-update --rules standard 